export const PROJECTS_PREVIEW: any = [
  {
    projectName: "clearancespot",
    slug: "clearancespot",
    title: "Clearancespot",
    subtitle: "Cheaper shopping",
    text: "Centralized database and website of all clearance items offered by different retailers. This product solves a problem that consumers do not have a single website to search for clearance items across multiple brands and companies.",
    image: "/gallery/projects/clearancespot/clearance-spot-logo.png",
    color: "#E05050",
  },
  {
    projectName: "speaksubz",
    slug: "speaksubz",
    title: "Speaksubz",
    subtitle: "Next-gen subtitle translation",
    text: "Subtitles for your favourite movies or TV shows can now be translated using text to speech allowing much faster translating time. This is also a mobile-friendly app, allowing the translators to work on their tablets or mobile-phones",
    image: "/gallery/projects/speaksubz/speaksubz-mockup.png",
    color: "#27A844",
  },
  {
    projectName: "fasting",
    slug: "fasting",
    title: "My Fasting Pal",
    subtitle: "Fasting Diet Tracker",
    text: "Native iOS app for monitoring a fasting diet, with smart fasting timer, personalized fasting presets and statistics",
    image: "/gallery/projects/fasting/fasting-logo.png",
    color: "#FF7954",
  },
  {
    projectName: "keto",
    slug: "keto",
    title: "My Keto Pal",
    subtitle: "Keto Diet & Low Carb Counter",
    text: "Fully fledged Keto Diet tracking app, with Apple Subscriptions, In-App shop (purchasable via CC or Apple Pay), Health Kit calorie tracking, custom recipe editor, barcode scanner, push notifications, daily planner, macro planer and more.",
    image: "/gallery/projects/keto/keto-logo.png",
    color: "#00aa5c",
  },
];
